action.py: Support adding labels only for specific modules
zephyrproject-rtos/action-manifest pull request #2
Opened 2021-06-13 12:24 UTC by oyvindronningstad

Specify as "<label>[:<module-name>[;<module-name>[;...]]]"

Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

2021-06-16 11:08 UTC, tejlmand requested changes
How about a bit more info on the commit message ?
>  action.py: Support adding labels only for specific modules
>
> Specify as "<label>[:<module-name>[;<module-name>[;...]]]"

2021-06-16 11:08 UTC, tejlmand commented on action.yml
> +    description: 'Comma-separated list of labels with optional module name filter: <label>[:<module-name>[;<module-name>[;...]]]'
Could you add an example, and some reference to where this is used (sdk-nrf).
That will make it easier for other who might need to update code, or use this in other repos.
That way they have a reference point on how to use.

2021-06-23 08:39 UTC, oyvindronningstad commented on action.yml
> +    description: 'Comma-separated list of labels with optional module name filter: <label>[:<module-name>[;<module-name>[;...]]]'
Added an example in the description. I'm not sure if adding a link to sdk-nrf is desirable, since the link might go stale, or the usage might change.

2021-06-23 08:39 UTC, oyvindronningstad commented
@tejlmand Added an example in the description and in the commit message.

2021-06-29 23:33 UTC, mbolivar-nordic commented on action.py
> +            get_modules = lambda l: map(str.strip, l.split(':')[1].split(';'))
I'm being lazy :P. Did you test this with a `labels` input that doesn't have a `:` in it? Does it still work unchanged?

2021-06-29 23:33 UTC, mbolivar-nordic commented
@oyvindronningstad since Carles and Torsten are on vacation, I'll try to help get this merged. I think this makes a lot of sense to get upstream but I want to make sure this is done in a backwards compatible way for existing upstream users.

2021-06-30 11:23 UTC, oyvindronningstad commented on action.py
> +            get_modules = lambda l: map(str.strip, l.split(':')[1].split(';'))
:) It's tested here at least: https://github.com/nrfconnect/sdk-nrf/pull/4817/files#diff-8f978e7d09ba31d15dfbb613f22827cc7943f7bb13b75d6656b649d000fbf90bR38

2021-07-14 19:56 UTC, mbolivar-nordic approved these changes

2021-07-14 19:56 UTC, mbolivar-nordic commented
@tejlmand please revisit

2021-07-15 11:48 UTC, tejlmand approved these changes
LGTM

2021-08-06 07:09 UTC, thst-nordic approved these changes

2021-08-06 17:32 UTC, carlescufi requested changes
Small change request, otherwise I'm fine with it.

2021-08-06 17:32 UTC, carlescufi commented on action.py
> +        if label_list:
This is redundant, already checked by the caller

2021-08-13 13:14 UTC, oyvindronningstad commented on action.py
> +        if label_list:
Removed

2021-08-16 17:09 UTC, carlescufi approved these changes

2021-08-16 17:09 UTC, merged