action: match revisions with a refs/ prefix
zephyrproject-rtos/action-manifest pull request #6
Opened 2022-12-22 13:12 UTC by fabiobaltieri

Make sure that the DNM tag triggers with both "pull/.../head" and "refs/pull/.../head" format.

```
>>> print(re.compile(r'(refs/|)pull/(\d+)/head').match("pull/123/head"))
<re.Match object; span=(0, 13), match='pull/123/head'>
>>> print(re.compile(r'(refs/|)pull/(\d+)/head').match("refs/pull/123/head"))
<re.Match object; span=(0, 18), match='refs/pull/123/head'>
>>> print(re.compile(r'(refs/|)pull/(\d+)/head').match("123"))
None
```

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>

2022-12-22 13:24 UTC, stephanosio requested changes

2022-12-22 13:24 UTC, stephanosio commented on action.py
> +    re_rev = re.compile(r'(refs/|)pull/(\d+)/head')
This is going to break the pull request number extraction logic below:
https://github.com/zephyrproject-rtos/action-manifest/blob/cca966c942e89147334ac353c8272b1d62e09043/action.py#L387

It now needs to reference the index `[2]` with this change.

2022-12-22 15:22 UTC, fabiobaltieri commented on action.py
> +    re_rev = re.compile(r'(refs/|)pull/(\d+)/head')
Oh, missed it, thanks, fixed both.

2022-12-22 15:25 UTC, fabiobaltieri commented on action.py
> +    re_rev = re.compile(r'(refs/|)pull/(\d+)/head')
Oh I see what ?: does :-) ok changed to yours and kept [1]

2022-12-22 15:25 UTC, stephanosio requested changes

2022-12-22 15:25 UTC, stephanosio commented on action.py
> +    re_rev = re.compile(r'(?:refs)?pull/(\d+)/head')
```suggestion
    re_rev = re.compile(r'(?:refs/)?pull/(\d+)/head')
```

2022-12-22 15:26 UTC, stephanosio approved these changes

2022-12-22 15:27 UTC, fabiobaltieri commented on action.py
> +    re_rev = re.compile(r'(?:refs)?pull/(\d+)/head')
Thanks :-)

2022-12-27 12:19 UTC, carlescufi approved these changes

2022-12-27 12:19 UTC, merged